<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MonoPraksa.Model</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeatherForecast.Common\MonoPraksa.Common.csproj" />
  </ItemGroup>

</Project>
