<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\WeatherForecast.Common\MonoPraksa.Common.csproj" />
		<ProjectReference Include="..\WeatherForecast.Model\MonoPraksa.Model.csproj" />
	</ItemGroup>

</Project>
