<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MonoPraksa.WebApi</RootNamespace>
    <UserSecretsId>c88ec01d-68a9-472c-b63a-baff1dabb2cf</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.31">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeatherForecast.Common\MonoPraksa.Common.csproj" />
    <ProjectReference Include="..\WeatherForecast.Model\MonoPraksa.Model.csproj" />
    <ProjectReference Include="..\WeatherForecast.Service\MonoPraksa.Service.csproj" />
  </ItemGroup>

</Project>
