<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>MonoPraksa.WebApi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WeatherForecast.Common\MonoPraksa.Common.csproj" />
    <ProjectReference Include="..\WeatherForecast.Model\MonoPraksa.Model.csproj" />
    <ProjectReference Include="..\WeatherForecast.Service\MonoPraksa.Service.csproj" />
  </ItemGroup>

</Project>
